# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Submit a new nightly build to Play Store."
  lane :nightly do |options|
    # Switch to the root directory to run the release script.
    # https://docs.fastlane.tools/advanced/fastlane/#directory-behavior
    Dir.chdir("..") do
      sh "ci/nightly-build.sh"
    end

#     upload_to_play_store(
#       package_name: "social.firefly.nightly",
#       aab: "secrets/firefly-nightly.aab",
#       track: "alpha",
#       skip_upload_metadata: true,
#     )

    set_github_release(
        repository_name: "Firefly-Social/Firefly",
        api_bearer: options[:token],
        name: options[:name],
        tag_name: options[:tag],
        is_prerelease: true,
        is_generate_release_notes: true,
        upload_assets: ["secrets/firefly-nightly.apk", "secrets/firefly-nightly.aab"]
    )
  end
end
